### ISSUE TITLE
can i try this in openlane's yosys.

### ISSUE THREAD

**Issue by Vinayakamk** [AUCOHL/Lighter#15]
this is more over question instaed technical issue
i thought of integrate automatic clock gating in openlane's yosys.

how can i do it?
plese let me know or if u have any resources plese do share the link!

thanks in advance!!

**Comment by kanndil** [comment]
Hello @Vinayakamk, we are glade that you are finding Lighter helpful. There are two ways of integrating Lighter into any version of Yosys:

1. Follow the [How To Use](https://github.com/AUCOHL/Lighter#-how-to-use) instructions in the Readme. 
---> This will basically wrap Lighter as a Yosys plugin and automatically insert it into your system. 

2. Lighter is also integrated with the [yosys-f4pga-plugins repo](https://github.com/chipsalliance/yosys-f4pga-plugins) where you can also install the clock gating plugin into Yosys along with a collection of other helpful plugins. Follow the instructions in their Repo for more details.

**Comment by Vinayakamk** [comment]
hello thank for the reply.
im confused while installing.
i installed dependencies in yosys.
now if i put this command for craeting plugin (yosys-config --build cg_plugin.so clock_gating_plugin.cc)
i got this error 
![image](https://github.com/AUCOHL/Lighter/assets/137029135/6d58c3af-8ffc-44f3-9601-776def65330c)


do i need to do installing all this inside lighter folder ??where plugins are there?

**Comment by Vinayakamk** [comment]
thanks for the reply,
but read_liberty of that standard cell liberty sky130_fd_sc_hd.lib,skipped most of the cells
may be it is issue of .lib or yosys.

but power reduced it seems in my design.
thank you

**Comment by Vinayakamk** [comment]
and also i have doubt,do i need to do to plugin every time.if i close terminal.
im confused as i open other terminal with same directory where i have installed minconda,i got this error
![image](https://github.com/AUCOHL/Lighter/assets/137029135/905defdb-c96b-4c58-abf2-6c70c9bd659b)

**Comment by kanndil** [comment]
Yes exactly. In the case of the first option, you must use this command every time to insert the plugin into Yosys. 
`yosys -m cg_plugin.so your_script.tcl`
And cg_plugin.so file must exist in your working directory. Which is generated using the following command:
`yosys-config --build cg_plugin.so clock_gating_plugin.cc`

**Comment by kanndil** [comment]
If you choose to use the other option, that is using this repo [yosys-f4pga-plugins repo](https://github.com/chipsalliance/yosys-f4pga-plugins), you would need to install it only once into your system.

**Comment by kanndil** [comment]
@Vinayakamk

**Comment by Vinayakamk** [comment]
got it.thanks a lot for the reply

im searched documentation to install 2nd type [yosys-f4pga-plugins repo](https://github.com/chipsalliance/yosys-f4pga-plugins)

may i get it??

thank you again for such an effort to implement the great and cool optimization -clcok gating

**Comment by kanndil** [comment]
@Vinayakamk You should just clone the repo and run `make install` in the main directory.

**Comment by Vinayakamk** [comment]
i got it,thank you so much for the reply

**Comment by kanndil** [comment]
Welcome
