### ISSUE TITLE
Installation Issue.

### ISSUE THREAD

**Issue by Dandy201** [AUCOHL/Lighter#20]
I've installed the dependencies as required. However when I open the terminal and enter the command : yosys-config --build cg_plugin.so clock_gating_plugin.cc, I get this. Is there something I'm missing?
![image](https://github.com/user-attachments/assets/88b7f25f-ce76-4eba-a11b-b9f98bf53ca2)

**Comment by kanndil** [comment]
you need to clone the repo and run this command in the src/ directory

here https://github.com/AUCOHL/Lighter/blob/main/src/clock_gating_plugin.cc
